# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [1]:
import numpy as np
print(np.zeros((2, 3)),'np.zeros是內容皆為0的陣列')
print(np.empty((2, 3)),'np.empty是內容不確定的陣列')

[[0. 0. 0.]
 [0. 0. 0.]] np.zeros是內容皆為0的陣列
[[0. 0. 0.]
 [0. 0. 0.]] np.empty是內容不確定的陣列


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [2]:
import numpy as np
a = np.random.random((2,3))*100
print(a)
np.set_printoptions(precision=0)
print(a)

[[22.00355066 11.66309692 90.8338337 ]
 [73.37054143 42.0459419  42.20049064]]
[[22. 12. 91.]
 [73. 42. 42.]]


In [4]:
# 參考解答

a = np.random.rand(2, 3)

'''
Your Code
'''

[[26.59948885 47.53904807 54.11469174]
 [70.68669942  6.86886691  4.57672874]]
[[27. 48. 54.]
 [71.  7.  5.]]
[[27. 48. 54.]
 [71.  7.  5.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [3]:
m = 20
n = 40
a = np.random.randint(m,n,size=(2,3))
print(a)

[[24 24 34]
 [33 34 36]]
