# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
import numpy as np
a=np.arange(6)
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 

15
15
15


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [3]:
A = np.random.random((5, 5))
print(A)
x=A.max()-A.min()
B=(A-A.min())/x
print(B)

[[0.01095625 0.3099935  0.95639478 0.29710717 0.61329619]
 [0.14448786 0.52292435 0.1110666  0.35530693 0.16003246]
 [0.69389122 0.38726471 0.13110974 0.60140889 0.05616249]
 [0.07580066 0.81095876 0.68809905 0.37325349 0.96122315]
 [0.28799617 0.73043268 0.21157559 0.2904157  0.33249792]]
[[0.         0.31468764 0.99491893 0.3011269  0.63386396]
 [0.14052011 0.53876242 0.10534971 0.36237259 0.15687824]
 [0.71867701 0.39600292 0.12644183 0.62135453 0.04757215]
 [0.06823809 0.84187139 0.7125817  0.3812584  1.        ]
 [0.29153906 0.7571309  0.21111894 0.29408521 0.33836985]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [ ]:
c=np.random.randint(1,100,size=10)
c.sort()
print(c)
c[9]=-1
print(c)

[ 0.29347583  0.59303277 -1.          0.38043546  0.63265939  0.32472618
  0.11340241  0.68136955  0.89905432  0.74769935]
